version: '3.8'

services:
  mongo:
    container_name: mongo-container
    image: mongo:7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  api:
    container_name: api-container
    build:
      context: .
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
